[2025-07-09T12:04:53.485+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-07-09T09:42:37.547378+00:00 [queued]>
[2025-07-09T12:04:53.500+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-07-09T09:42:37.547378+00:00 [queued]>
[2025-07-09T12:04:53.500+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-07-09T12:04:53.500+0200] {taskinstance.py:1280} INFO - Starting attempt 3 of 4
[2025-07-09T12:04:53.500+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-07-09T12:04:53.518+0200] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2025-07-09 09:42:37.547378+00:00
[2025-07-09T12:04:53.521+0200] {standard_task_runner.py:55} INFO - Started process 96008 to run task
[2025-07-09T12:04:53.523+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', 'manual__2025-07-09T09:42:37.547378+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpybifmc21']
[2025-07-09T12:04:53.525+0200] {standard_task_runner.py:83} INFO - Job 62: Subtask pyspark_train_classifier_model
[2025-07-09T12:04:53.624+0200] {task_command.py:388} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-07-09T09:42:37.547378+00:00 [running]> on host l013.lab.dit.upm.es
[2025-07-09T12:04:53.744+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2025-07-09T09:42:37.547378+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-07-09T09:42:37.547378+00:00
[2025-07-09T12:04:53.747+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-09T12:04:53.748+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nspark-submit --master local[4]   /home/monica.fernandez/practica_creativa/resources/train_spark_mllib_model.py   /home/monica.fernandez/practica_creativa']
[2025-07-09T12:04:53.762+0200] {subprocess.py:86} INFO - Output:
[2025-07-09T12:04:55.280+0200] {subprocess.py:93} INFO - 25/07/09 12:04:55 WARN Utils: Your hostname, l013 resolves to a loopback address: 127.0.1.1; using 138.4.31.13 instead (on interface enp1s0)
[2025-07-09T12:04:55.282+0200] {subprocess.py:93} INFO - 25/07/09 12:04:55 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-07-09T12:04:55.410+0200] {subprocess.py:93} INFO - Exception in thread "main" java.lang.IllegalArgumentException: basedir must be absolute: ?/.ivy2/local
[2025-07-09T12:04:55.410+0200] {subprocess.py:93} INFO - 	at org.apache.ivy.util.Checks.checkAbsolute(Checks.java:48)
[2025-07-09T12:04:55.410+0200] {subprocess.py:93} INFO - 	at org.apache.ivy.plugins.repository.file.FileRepository.setBaseDir(FileRepository.java:137)
[2025-07-09T12:04:55.410+0200] {subprocess.py:93} INFO - 	at org.apache.ivy.plugins.repository.file.FileRepository.<init>(FileRepository.java:44)
[2025-07-09T12:04:55.410+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.createRepoResolvers(SparkSubmit.scala:1269)
[2025-07-09T12:04:55.410+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.buildIvySettings(SparkSubmit.scala:1376)
[2025-07-09T12:04:55.410+0200] {subprocess.py:93} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:182)
[2025-07-09T12:04:55.410+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:334)
[2025-07-09T12:04:55.411+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
[2025-07-09T12:04:55.411+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2025-07-09T12:04:55.411+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2025-07-09T12:04:55.411+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2025-07-09T12:04:55.411+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2025-07-09T12:04:55.411+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2025-07-09T12:04:55.411+0200] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-07-09T12:04:55.452+0200] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-09T12:04:55.467+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-09T12:04:55.473+0200] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20250709T094237, start_date=20250709T100453, end_date=20250709T100455
[2025-07-09T12:04:55.498+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 62 for task pyspark_train_classifier_model (Bash command failed. The command returned a non-zero exit code 1.; 96008)
[2025-07-09T12:04:55.540+0200] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-07-09T12:04:55.572+0200] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
