[2025-06-16T18:52:31.724+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-16T16:34:35.725251+00:00 [queued]>
[2025-06-16T18:52:31.739+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-16T16:34:35.725251+00:00 [queued]>
[2025-06-16T18:52:31.739+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-06-16T18:52:31.739+0200] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2025-06-16T18:52:31.739+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-06-16T18:52:31.757+0200] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2025-06-16 16:34:35.725251+00:00
[2025-06-16T18:52:31.759+0200] {standard_task_runner.py:55} INFO - Started process 218791 to run task
[2025-06-16T18:52:31.762+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', 'manual__2025-06-16T16:34:35.725251+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmp8yvwehrv']
[2025-06-16T18:52:31.763+0200] {standard_task_runner.py:83} INFO - Job 11: Subtask pyspark_train_classifier_model
[2025-06-16T18:52:31.833+0200] {task_command.py:388} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-16T16:34:35.725251+00:00 [running]> on host l014.lab.dit.upm.es
[2025-06-16T18:52:31.906+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2025-06-16T16:34:35.725251+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-16T16:34:35.725251+00:00
[2025-06-16T18:52:31.907+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-16T18:52:31.908+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nspark-submit --master local[4]   None//resources/train_spark_mllib_model.py   None/\n  ']
[2025-06-16T18:52:31.914+0200] {subprocess.py:86} INFO - Output:
[2025-06-16T18:52:33.200+0200] {subprocess.py:93} INFO - 25/06/16 18:52:33 WARN Utils: Your hostname, l014 resolves to a loopback address: 127.0.1.1; using 138.4.31.14 instead (on interface enp1s0)
[2025-06-16T18:52:33.202+0200] {subprocess.py:93} INFO - 25/06/16 18:52:33 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-06-16T18:52:33.585+0200] {subprocess.py:93} INFO - python3: can't open file '/tmp/airflowtmpycz4dqag/None/resources/train_spark_mllib_model.py': [Errno 2] No such file or directory
[2025-06-16T18:52:33.593+0200] {subprocess.py:93} INFO - 25/06/16 18:52:33 INFO ShutdownHookManager: Shutdown hook called
[2025-06-16T18:52:33.594+0200] {subprocess.py:93} INFO - 25/06/16 18:52:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-33fb20ab-f3b0-45dc-b3a7-173d66c21261
[2025-06-16T18:52:33.624+0200] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-16T18:52:33.640+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-16T18:52:33.645+0200] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20250616T163435, start_date=20250616T165231, end_date=20250616T165233
[2025-06-16T18:52:33.669+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 11 for task pyspark_train_classifier_model (Bash command failed. The command returned a non-zero exit code 2.; 218791)
[2025-06-16T18:52:33.674+0200] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-06-16T18:52:33.695+0200] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
