[2025-06-11T18:01:13.096+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:45:16.263513+00:00 [queued]>
[2025-06-11T18:01:13.139+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:45:16.263513+00:00 [queued]>
[2025-06-11T18:01:13.139+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-06-11T18:01:13.139+0200] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2025-06-11T18:01:13.139+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-06-11T18:01:13.175+0200] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2025-06-11 15:45:16.263513+00:00
[2025-06-11T18:01:13.187+0200] {standard_task_runner.py:55} INFO - Started process 186164 to run task
[2025-06-11T18:01:13.198+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', 'manual__2025-06-11T15:45:16.263513+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpa4p0ljqm']
[2025-06-11T18:01:13.200+0200] {standard_task_runner.py:83} INFO - Job 31: Subtask pyspark_train_classifier_model
[2025-06-11T18:01:13.309+0200] {task_command.py:388} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-11T15:45:16.263513+00:00 [running]> on host l090.lab.dit.upm.es
[2025-06-11T18:01:13.447+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2025-06-11T15:45:16.263513+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-11T15:45:16.263513+00:00
[2025-06-11T18:01:13.449+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-11T18:01:13.450+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nspark-submit --master local[4]   /home/monica.fernandez/practica_creativa//resources/train_spark_mllib_model.py   /home/monica.fernandez/practica_creativa/']
[2025-06-11T18:01:13.464+0200] {subprocess.py:86} INFO - Output:
[2025-06-11T18:01:16.944+0200] {subprocess.py:93} INFO - 25/06/11 18:01:16 WARN Utils: Your hostname, l090 resolves to a loopback address: 127.0.1.1; using 138.4.31.90 instead (on interface enp3s0)
[2025-06-11T18:01:16.948+0200] {subprocess.py:93} INFO - 25/06/11 18:01:16 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-06-11T18:01:17.698+0200] {subprocess.py:93} INFO -   File "/home/monica.fernandez/practica_creativa/resources/train_spark_mllib_model.py", line 185
[2025-06-11T18:01:17.699+0200] {subprocess.py:93} INFO -     evaluator = MulticlassClassificationEvaluator(
[2025-06-11T18:01:17.699+0200] {subprocess.py:93} INFO - IndentationError: unexpected indent
[2025-06-11T18:01:17.727+0200] {subprocess.py:93} INFO - 25/06/11 18:01:17 INFO ShutdownHookManager: Shutdown hook called
[2025-06-11T18:01:17.734+0200] {subprocess.py:93} INFO - 25/06/11 18:01:17 INFO ShutdownHookManager: Deleting directory /tmp/spark-d867e39d-613f-4b5e-bd86-c76c02032eee
[2025-06-11T18:01:17.780+0200] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-11T18:01:17.797+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-11T18:01:17.802+0200] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20250611T154516, start_date=20250611T160113, end_date=20250611T160117
[2025-06-11T18:01:17.839+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 31 for task pyspark_train_classifier_model (Bash command failed. The command returned a non-zero exit code 1.; 186164)
[2025-06-11T18:01:17.887+0200] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-06-11T18:01:17.926+0200] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
