[2025-06-16T18:52:10.894+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-16T16:39:27.989046+00:00 [queued]>
[2025-06-16T18:52:10.919+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-16T16:39:27.989046+00:00 [queued]>
[2025-06-16T18:52:10.920+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-06-16T18:52:10.920+0200] {taskinstance.py:1280} INFO - Starting attempt 4 of 4
[2025-06-16T18:52:10.920+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-06-16T18:52:10.951+0200] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): pyspark_train_classifier_model> on 2025-06-16 16:39:27.989046+00:00
[2025-06-16T18:52:10.955+0200] {standard_task_runner.py:55} INFO - Started process 218557 to run task
[2025-06-16T18:52:10.961+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'agile_data_science_batch_prediction_model_training', 'pyspark_train_classifier_model', 'manual__2025-06-16T16:39:27.989046+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/setup.py', '--cfg-path', '/tmp/tmpzvbshjn_']
[2025-06-16T18:52:10.964+0200] {standard_task_runner.py:83} INFO - Job 10: Subtask pyspark_train_classifier_model
[2025-06-16T18:52:11.084+0200] {task_command.py:388} INFO - Running <TaskInstance: agile_data_science_batch_prediction_model_training.pyspark_train_classifier_model manual__2025-06-16T16:39:27.989046+00:00 [running]> on host l014.lab.dit.upm.es
[2025-06-16T18:52:11.206+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=agile_data_science_batch_prediction_model_training
AIRFLOW_CTX_TASK_ID=pyspark_train_classifier_model
AIRFLOW_CTX_EXECUTION_DATE=2025-06-16T16:39:27.989046+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-06-16T16:39:27.989046+00:00
[2025-06-16T18:52:11.208+0200] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-06-16T18:52:11.208+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nspark-submit --master local[4]   None//resources/train_spark_mllib_model.py   None/\n  ']
[2025-06-16T18:52:11.220+0200] {subprocess.py:86} INFO - Output:
[2025-06-16T18:52:12.663+0200] {subprocess.py:93} INFO - 25/06/16 18:52:12 WARN Utils: Your hostname, l014 resolves to a loopback address: 127.0.1.1; using 138.4.31.14 instead (on interface enp1s0)
[2025-06-16T18:52:12.665+0200] {subprocess.py:93} INFO - 25/06/16 18:52:12 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-06-16T18:52:13.001+0200] {subprocess.py:93} INFO - python3: can't open file '/tmp/airflowtmp3vl662yh/None/resources/train_spark_mllib_model.py': [Errno 2] No such file or directory
[2025-06-16T18:52:13.013+0200] {subprocess.py:93} INFO - 25/06/16 18:52:13 INFO ShutdownHookManager: Shutdown hook called
[2025-06-16T18:52:13.014+0200] {subprocess.py:93} INFO - 25/06/16 18:52:13 INFO ShutdownHookManager: Deleting directory /tmp/spark-8c28569d-8f93-451d-b7ce-fd14ba44be28
[2025-06-16T18:52:13.104+0200] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-16T18:52:13.140+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/monica.fernandez/practica_creativa/venv-airflow/lib/python3.11/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-16T18:52:13.151+0200] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=agile_data_science_batch_prediction_model_training, task_id=pyspark_train_classifier_model, execution_date=20250616T163927, start_date=20250616T165210, end_date=20250616T165213
[2025-06-16T18:52:13.195+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 10 for task pyspark_train_classifier_model (Bash command failed. The command returned a non-zero exit code 2.; 218557)
[2025-06-16T18:52:13.227+0200] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-06-16T18:52:13.278+0200] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
